[build]
  command = "next run build && next run start"
  publish = "out"
  target = "serverless"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"